spring.application.name=Agricultural Marketing Digitization

spring.profiles.active=dev
server.servlet.context-path=/doam
server.port=8087

spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000