spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://nidhi-development.cluster-cxk6bpizs4jb.ap-south-1.rds.amazonaws.com:3306/apdbt
spring.datasource.username=apdbt_admin
spring.datasource.password=ApDbt@2024


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
